INSERT INTO USR (ID, PASSWORD, USERNAME) VALUES (1, '$2a$12$faQDzzrXYuHym9TodepWE.9Jn8RJwepB5KLho7t2iAJSJFoB/ax1.', 'Jack');
INSERT INTO USR (ID, PASSWORD, USERNAME) VALUES (2, '$2a$12$faQDzzrXYuHym9TodepWE.9Jn8RJwepB5KLho7t2iAJSJFoB/ax1.', 'Anna');
